apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pcos-fase2-api
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containers:
        - image: REGION-docker.pkg.dev/PROJECT_ID/REPOSITORY/pcos-fase2-api:latest
          ports:
            - containerPort: 8000
          env:
            - name: LLM_PROVIDER
              value: mock
            - name: LLM_MODEL
              value: gemini-2.5-flash-lite
            - name: PREDICTION_THRESHOLD
              value: "0.50"
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
